name: CICD

on:
  push:
    branches: 
      - main
    
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Source
        uses: actions/checkout@v3
      - name: Set Node.js version
        uses: actions/setup-node
        with:
          node-version: '20.x'
      - name: Install Dependencies
        run : npm install
      - name: Deploy to Azure App service
        run: npm test
